version: '3.8'

services:
  siren-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siren-stream
    network_mode: host
    volumes:
      - ./music:/app/music
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    command: python stream_audio.py
