services:
  siren-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siren-stream
    network_mode: host
    volumes:
      - ./music:/app/music
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    sysctls:
      - net.core.rmem_max=2097152
      - net.core.wmem_max=2097152
      - net.ipv4.igmp_max_memberships=256
    command: python stream_audio.py
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
