services:
  siren-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siren-stream
    network_mode: host
    volumes:
      - ./music:/app/music
    restart: unless-stopped
    environment:
      - MUSIC_FOLDER=${MUSIC_FOLDER:-music/}
      - DEFAULT_DEVICE=${DEFAULT_DEVICE:-Bedroom speaker}
      - PORT=${PORT:-5067}
      - LOOP_DELAY=${LOOP_DELAY:-0.1}
      - DEFAULT_VOLUME=${DEFAULT_VOLUME:-5}
    command: python stream_audio.py
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
